agent_name: ocean_buyer
author: fetchai
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.1.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- eightballer/ocean:0.1.0
- fetchai/ledger:0.19.0
- fetchai/p2p_libp2p:0.25.0
- fetchai/soef:0.26.0
contracts: []
protocols:
- eightballer/ocean:0.1.0
- fetchai/acn:1.0.0
- fetchai/contract_api:1.0.0
- fetchai/default:1.0.0
- fetchai/fipa:1.0.0
- fetchai/ledger_api:1.0.0
- fetchai/oef_search:1.0.0
- fetchai/signing:1.0.0
- fetchai/state_update:1.0.0
skills:
- eightballer/ocean_buyer:0.1.0
default_connection: fetchai/p2p_libp2p:0.25.0
default_ledger: fetchai
required_ledgers:
- fetchai
default_routing:
  fetchai/ledger_api:1.0.0: fetchai/ledger:0.19.0
  fetchai/oef_search:1.0.0: fetchai/soef:0.26.0
connection_private_key_paths:
  fetchai: fetchai_private_key.txt
private_key_paths:
  fetchai: fetchai_private_key.txt
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  aea-ledger-fetchai: {}
---
public_id: fetchai/p2p_libp2p:0.25.0
type: connection
config:
  delegate_uri: null
  entry_peers:
  - /dns4/acn.fetch.ai/tcp/9000/p2p/16Uiu2HAkw1ypeQYQbRFV5hKUxGRHocwU5ohmVmCnyJNg36tnPFdx
  - /dns4/acn.fetch.ai/tcp/9001/p2p/16Uiu2HAmVWnopQAqq4pniYLw44VRvYxBUoRHqjz1Hh2SoCyjbyRW
  public_uri: null
  local_uri: 127.0.0.1:9000
---
public_id: eightballer/ocean:0.1.0
type: connection
config:
  ocean_network_url: https://rpc.polygon.oceanprotocol.com
  key_path: ethereum_private_key.txt
---
public_id: fetchai/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: https://rpc.polygon.oceanprotocol.com
