##
## Copyright 2021 Ocean Protocol Foundation
## SPDX-License-Identifier: Apache-2.0
##
name: Oceansimpleseller tests

on:
  - push
  - pull_request

jobs:
  build:
    environment: CC_REPORTER_ID
    runs-on: ubuntu-latest
    steps:
      - name: Setup Oceansimpleseller
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/checkout@v2
        name: Checkout Barge
        with:
          repository: "oceanprotocol/barge"
          path: 'barge'
          ref: v3
      - name: Run Barge
        working-directory: ${{ github.workspace }}/barge
        env:
          OPERATOR_SERVICE_URL: https://c2d-dev.operator.oceanprotocol.com/
        run: |
          bash -x start_ocean.sh --no-dashboard 2>&1 --with-provider2 --with-rbac > start_ocean.log &
          for i in $(seq 1 50); do
            sleep 5
            [ -f "$HOME/.ocean/ocean-contracts/artifacts/ready" ] && break
            done
          ls -la "$HOME/.ocean/ocean-contracts/artifacts/"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          pipenv install --dev --skip-lock
          pipenv run pip install pytest pytest-env
      - name: Run tests
        working-directory: ${{ github.workspace }}
        env:
          FETCH_URL: https://rest-capricorn.fetch.ai:443
          FETCH_DENOM: atestfet
          FETCH_CHAIN_ID: capricorn-1
          SELLER_AEA_KEY_ETHEREUM: "0x8467415bb2ba7c91084d932276214b11a3dd9bdb2930fefa194b666dd8020b99"
          SELLER_AEA_KEY_FETCHAI: "1437aebfadbb766b810894a7859db3574088e6909f229e484e2e14e00b7c0875"
          BUYER_AEA_KEY_ETHEREUM: "0xef4b441145c1d0f3b4bc6d61d29f5c6e502359481152f869247c7a4244d45209"
          BUYER_AEA_KEY_FETCHAI: "670c081eb3f674ae55e28ab714e7393abc74346a6fc738b1bf245140a038a3bb"
          STORJ_ENDPOINT: https://gateway.eu1.storjshare.io
          STORJ_ACCESS_KEY: j2wulv3drlgrt5apjr2csc5lmkzyqpqakgzuoc63fn6wedxmnu2ng
          STORJ_ACCESS_KEY_ID: jx7bgg74ceog3eznrovaiqcy23sa
          TARGET_SKILL: eightballer/storj_file_transfer:0.1.0
          RPC_URL: http://127.0.0.1:8545
          ADDRESS_FILE: ~/.ocean/ocean-contracts/artifacts/address.json
          OCEAN_NETWORK_URL: http://127.0.0.1:8545
        run: |
          echo -n $SELLER_AEA_KEY_ETHEREUM > "ethereum_private_key.txt"
          pipenv run python -m pytest
